//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize, Default)]
#[sea_orm(table_name = "oss_obj_ref")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, unique)]
    pub id: i64,
    pub obj_id: i64,
    pub bucket_id: i64,
    pub name: String,
    pub ext: Option<String>,
    pub creator_id: i64,
    pub create_ts: i64,
    pub updator_id: i64,
    pub update_ts: i64,
    #[sea_orm(unique)]
    pub download_url: String,
    pub preview_url: Option<String>,
    #[sea_orm(
        belongs_to,
        from = "bucket_id",
        to = "id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    pub oss_bucket: BelongsTo<super::oss_bucket::Entity>,
    #[sea_orm(
        belongs_to,
        from = "obj_id",
        to = "id",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    pub oss_obj: BelongsTo<super::oss_obj::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
