//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "oss_obj")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, unique)]
    pub id: i64,
    pub name: String,
    pub bucket: String,
    pub path: Option<String>,
    pub size: Option<i64>,
    pub url: Option<String>,
    pub creator_id: Option<i64>,
    pub create_timestamp: Option<i64>,
    pub updator_id: Option<i64>,
    pub update_timestamp: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
