-- 修正约束名称：AK_SIZE_ANE_HASH_OSS_OBJ -> AK_SIZE_AND_HASH_OSS_OBJ
-- 删除错误的约束
ALTER TABLE oss_obj DROP CONSTRAINT IF EXISTS AK_SIZE_ANE_HASH_OSS_OBJ;

-- 添加正确的约束
ALTER TABLE oss_obj ADD CONSTRAINT AK_SIZE_AND_HASH_OSS_OBJ UNIQUE (size, hash);
