//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[sea_orm::model]
#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize, Default)]
#[sea_orm(table_name = "oss_obj")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, unique)]
    pub id: i64,
    pub is_completed: bool,
    #[sea_orm(unique)]
    pub path: String,
    #[sea_orm(unique_key = "ak_size_and_hash_oss_obj")]
    pub size: Option<i64>,
    #[sea_orm(unique_key = "ak_size_and_hash_oss_obj")]
    pub hash: Option<String>,
    pub creator_id: i64,
    pub create_ts: i64,
    pub updator_id: i64,
    pub update_ts: i64,
    #[sea_orm(has_many)]
    pub oss_obj_refs: HasMany<super::oss_obj_ref::Entity>,
}

impl ActiveModelBehavior for ActiveModel {}
